const inputValues = [
  {
    formId: 1,
    name: "firstName",
    type: "text",
    placeholder: "First Name",
    label: "First Name",
    value: "firstName",
    aria_label: "First Name Field",
    id: "first_name",
    style: "marginTop: 1rem",
  },
  {
    formId: 2,
    name: "lastName",
    type: "text",
    placeholder: "Last Name",
    label: "Last Name",
    value: "lastName",
    aria_label: "Last Name Field",
    id: "last_name",
  },
  {
    formId: 3,
    name: "email",
    type: "email",
    placeholder: "Email Address",
    label: "Email Address",
    value: "email",
    aria_label: "Email Address Field",
    id: "form_email",
  },
  {
    formId: 4,
    name: "password",
    type: "password",
    placeholder: "Password",
    label: "Password",
    value: "password",
    aria_label: "Password Field",
    id: "form_password",
  },
];

export default inputValues;
